import { spawnSync } from "node:child_process";
import { writeFileSync, mkdirSync, unlinkSync, existsSync, chmodSync } from "node:fs";
import { join, resolve } from "node:path";
import { homedir } from "node:os";
import { createLogger } from "../logging/logger.js";

const log = createLogger("beekeeper-service");

// Reverse-DNS label for the LaunchAgent. The real domain is keepur.io, so
// the reverse is io.keepur.beekeeper — NOT com.keepur.beekeeper (we do not
// own keepur.com).
const LABEL = "io.keepur.beekeeper";

/**
 * Resolve where the built index.js lives for this install.
 * In a normal `npm run build` checkout, dist/service/generate-plist.js is two
 * levels deep from dist/index.js.
 */
function resolveIndexPath(): string {
  return resolve(import.meta.dirname, "../index.js");
}

/**
 * Resolve the repo/source root that contains the `dist/` directory. At
 * runtime `import.meta.dirname` is `<repo>/dist/service`, so `..` is
 * `<repo>/dist` and `../..` is the repo root. This is where the wrapper
 * script gets written in wrapper mode.
 */
function resolveRepoRoot(): string {
  return resolve(import.meta.dirname, "../..");
}

/**
 * POSIX shell-quote: wrap in single quotes and escape any embedded single
 * quotes via the `'\''` dance. Safe for any byte sequence except NUL.
 * Used to embed runtime paths into the generated wrapper script so a
 * workDir containing `"`, `$`, or a backtick can't corrupt it.
 */
function shQuote(s: string): string {
  return "'" + s.replace(/'/g, "'\\''") + "'";
}

/**
 * Escape a string for safe inclusion inside an XML text node or attribute.
 * The plist format is XML; paths containing `&`, `<`, or `>` would
 * otherwise produce an invalid document.
 */
function xmlEscape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * Write a wrapper shell script that sources `envFile` and execs node on the
 * built index.js. Returns the absolute path to the wrapper. Idempotent —
 * overwrites on each install so a rebuild can't leave a stale wrapper
 * pointing at an old path.
 */
function writeWrapperScript(envFile: string, nodePath: string, indexPath: string): string {
  const wrapperDir = join(resolveRepoRoot(), "bin");
  const wrapperPath = join(wrapperDir, "start.sh");
  mkdirSync(wrapperDir, { recursive: true });

  // When launchd starts a gui/ LaunchAgent, the child process inherits a
  // minimal PATH (/usr/bin:/bin:/usr/sbin:/sbin) — no /opt/homebrew/bin, no
  // /usr/local/bin. That breaks any `spawn("node", ...)` or `spawn("git", ...)`
  // call from beekeeper or from tools Claude Code runs (bash, git, npm, etc.),
  // because the binaries aren't in that default PATH. We export a reasonable
  // PATH in the wrapper BEFORE sourcing the env file, so a user-provided
  // PATH= line in ~/.beekeeper/env still wins (it'll overwrite this default).
  const defaultPath = "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";

  const content = `#!/usr/bin/env bash
# Auto-generated by 'beekeeper install'. Regenerated on each install.
# Sources the env file (secrets + paths) and execs the built server.
set -euo pipefail

# Ensure a sane PATH for subprocess spawns (node, git, bash tools). launchd's
# default PATH omits /opt/homebrew/bin which breaks Claude Code's own tool
# use. Set BEFORE sourcing the env file so a user-provided PATH line in that
# file can still override this default.
export PATH=${shQuote(defaultPath)}

ENV_FILE=${shQuote(envFile)}
if [[ ! -f "\${ENV_FILE}" ]]; then
  echo "missing env file: \${ENV_FILE}" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
. "\${ENV_FILE}"
set +a

exec ${shQuote(nodePath)} ${shQuote(indexPath)}
`;

  writeFileSync(wrapperPath, content);
  chmodSync(wrapperPath, 0o755);
  return wrapperPath;
}

/**
 * Generate the plist XML. When `wrapperPath` is provided, the plist runs the
 * wrapper script instead of node directly (so secrets can be sourced from an
 * env file without being embedded in the plist).
 */
export function generatePlist(options: {
  configDir: string;
  wrapperPath?: string;
  nodePath: string;
  indexPath: string;
  logDir: string;
}): string {
  const { configDir, wrapperPath, nodePath, indexPath, logDir } = options;

  const programArgs = wrapperPath ? [wrapperPath] : [nodePath, indexPath];
  const programArgsXml = programArgs
    .map((arg) => `    <string>${xmlEscape(arg)}</string>`)
    .join("\n");

  // When a wrapper sources its own env file, the plist doesn't need to embed
  // BEEKEEPER_CONFIG. Direct-node mode still sets it for back-compat.
  const envVarsXml = wrapperPath
    ? ""
    : `  <key>EnvironmentVariables</key>
  <dict>
    <key>BEEKEEPER_CONFIG</key>
    <string>beekeeper.yaml</string>
  </dict>
`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${xmlEscape(LABEL)}</string>
  <key>ProgramArguments</key>
  <array>
${programArgsXml}
  </array>
  <key>WorkingDirectory</key>
  <string>${xmlEscape(configDir)}</string>
${envVarsXml}  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>${xmlEscape(logDir)}/beekeeper.log</string>
  <key>StandardErrorPath</key>
  <string>${xmlEscape(logDir)}/beekeeper.err</string>
</dict>
</plist>`;
}

/**
 * Install the LaunchAgent plist. If `${configDir}/env` exists, install
 * generates a wrapper script at `<repoRoot>/bin/start.sh` that sources the
 * env file, and points the plist at that wrapper. Otherwise, the plist runs
 * node directly (legacy mode — requires secrets to be in launchd's env).
 */
export function install(configDir?: string): void {
  const nodePath = process.execPath;
  const indexPath = resolveIndexPath();
  const workDir = configDir ?? join(homedir(), ".beekeeper");
  const logDir = join(workDir, "logs");
  mkdirSync(logDir, { recursive: true });

  const envFile = join(workDir, "env");
  const useWrapper = existsSync(envFile);
  let wrapperPath: string | undefined;
  if (useWrapper) {
    wrapperPath = writeWrapperScript(envFile, nodePath, indexPath);
    log.info("Wrapper script written", { path: wrapperPath, envFile });
  }

  const plistContent = generatePlist({
    configDir: workDir,
    wrapperPath,
    nodePath,
    indexPath,
    logDir,
  });
  const plistDir = join(homedir(), "Library", "LaunchAgents");
  const plistPath = join(plistDir, `${LABEL}.plist`);

  mkdirSync(plistDir, { recursive: true });
  writeFileSync(plistPath, plistContent);
  log.info("Plist installed", { path: plistPath, wrapper: useWrapper });

  console.log(`LaunchAgent installed: ${plistPath}`);
  if (useWrapper) {
    console.log(`Wrapper script: ${wrapperPath}`);
    console.log(`Sources env from: ${envFile}`);
  } else {
    console.log(`No ${envFile} found — plist runs node directly.`);
    console.log(`If you need secrets, either:`);
    console.log(`  - create ${envFile} with BEEKEEPER_JWT_SECRET / BEEKEEPER_ADMIN_SECRET and re-run install`);
    console.log(`  - or manually edit the plist's EnvironmentVariables`);
  }
  console.log(`Start with: launchctl load ${plistPath}`);
  console.log(`Stop with:  launchctl unload ${plistPath}`);
}

export function uninstall(): void {
  const plistPath = join(homedir(), "Library", "LaunchAgents", `${LABEL}.plist`);

  // spawnSync with an array avoids shell interpretation entirely.
  spawnSync("launchctl", ["unload", plistPath], { stdio: "ignore" });

  if (existsSync(plistPath)) {
    unlinkSync(plistPath);
    log.info("Plist removed", { path: plistPath });
    console.log(`LaunchAgent removed: ${plistPath}`);
  } else {
    console.log("No LaunchAgent found to remove.");
  }

  // Note: we intentionally do NOT delete the wrapper script under bin/start.sh.
  // It's harmless without the plist and users may still invoke it manually
  // from the shell.
}
